"""Work with bot's database."""

import os
import threading
from contextlib import contextmanager

import psycopg
from psycopg_pool import ConnectionPool
from paths import env_var

_initialized = False
_pool = None
_pool_lock = threading.Lock()


def get_dsn() -> str:
    """Return the connection string from the DATABASE_URL environment variable."""
    dsn = env_var("DATABASE_URL")
    if not dsn:
        raise RuntimeError("DATABASE_URL is not set. Example: postgresql://botuser:password@localhost:5432/botdb")
    return dsn


class Row(tuple):
    """Row that supports access by index and by column name, like sqlite3.Row."""

    def __new__(cls, names, values):
        row = super().__new__(cls, values)
        row._names = tuple(names)
        return row

    def __getitem__(self, key):
        if isinstance(key, str):
            try:
                return super().__getitem__(self._names.index(key))
            except ValueError:
                raise IndexError(f"No item with that key: {key}") from None
        return super().__getitem__(key)

    def keys(self):
        return list(self._names)


def _row_factory(cursor):
    """psycopg row factory that builds Row objects."""
    if not cursor.description: #no rows
        return lambda values: values
    names = [col.name for col in cursor.description]
    return lambda values: Row(names, values)


class _Cursor:
    """Thin wrapper over a psycopg cursor."""

    def __init__(self, cur):
        self._cur = cur

    def execute(self, sql, params=None):
        self._cur.execute(sql, params)
        return self

    def executemany(self, sql, seq_of_params):
        self._cur.executemany(sql, seq_of_params)
        return self

    def execute(self, sql, params=None):
        self._cur.execute(sql, params)
        return self

    def executemany(self, sql, seq_of_params):
        self._cur.executemany(sql, seq_of_params)
        return self

    def __iter__(self):
        return iter(self._cur)

    def __getattr__(self, name):
        # fetchone, fetchall, fetchmany, rowcount, description, ...
        return getattr(self._cur, name)


def _get_pool() -> ConnectionPool:
    global _pool
    if _pool is None:
        with _pool_lock:
            if _pool is None:
                _pool = ConnectionPool(
                    get_dsn(),
                    min_size=1,
                    max_size=10,
                    kwargs={"row_factory": _row_factory},
                    open=True,
                )
    return _pool


def get_connection() -> psycopg.Connection:
    """Open a standalone (non-pooled) connection. The caller must close it."""
    return psycopg.connect(get_dsn(), row_factory=_row_factory)


def close():
    """Close the connection pool."""
    global _pool
    if _pool is not None:
        _pool.close()
        _pool = None


@contextmanager
def db_cursor(commit: bool = False):
    """Context manager that yields a cursor and returns the connection to the pool.

    Pass commit=True for any operation that writes data.
    """
    with _get_pool().connection() as conn:
        with conn.cursor() as cur:
            yield _Cursor(cur)
        if commit:
            conn.commit()
        else:
            conn.rollback()


SCHEMA = """
CREATE TABLE IF NOT EXISTS warns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    moderator_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    duration_raw TEXT,
    created_at TEXT NOT NULL,
    expires_at TEXT,
    status TEXT NOT NULL DEFAULT 'active'
);
CREATE INDEX IF NOT EXISTS idx_warns_guild_user ON warns(guild_id, user_id);
CREATE INDEX IF NOT EXISTS idx_warns_status ON warns(status);

CREATE TABLE IF NOT EXISTS temp_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    moderator_id BIGINT NOT NULL,
    created_at TEXT NOT NULL,
    expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_temp_roles_expires ON temp_roles(expires_at);

CREATE TABLE IF NOT EXISTS triggers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    pattern TEXT NOT NULL,
    sort_order INTEGER NOT NULL,
    UNIQUE(guild_id, pattern)
);
CREATE TABLE IF NOT EXISTS trigger_responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trigger_id BIGINT NOT NULL REFERENCES triggers(id) ON DELETE CASCADE,
    response TEXT NOT NULL,
    sort_order INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_trigger_responses_trigger ON trigger_responses(trigger_id);

CREATE TABLE IF NOT EXISTS giveaways (
    message_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    host_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    prize TEXT,
    winners_count INTEGER NOT NULL DEFAULT 1,
    end_time TEXT NOT NULL,
    ended SMALLINT NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS giveaway_participants (
    giveaway_message_id BIGINT NOT NULL REFERENCES giveaways(message_id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (giveaway_message_id, user_id)
);

CREATE TABLE IF NOT EXISTS api_keys (
    guild_id BIGINT PRIMARY KEY,
    api_key TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ai_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role TEXT NOT NULL,
    content TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_memory_guild_user ON ai_memory(guild_id, user_id, id);

CREATE TABLE IF NOT EXISTS guild_locale (
    guild_id BIGINT PRIMARY KEY,
    localization TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS log_channels (
    guild_id BIGINT PRIMARY KEY,
    channel_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS permission_grants (
    guild_id BIGINT NOT NULL,
    target_type TEXT NOT NULL CHECK (target_type IN ('guild', 'user', 'role', 'channel')),
    target_id BIGINT NOT NULL,
    value BIGINT NOT NULL,
    PRIMARY KEY (guild_id, target_type, target_id)
);
CREATE INDEX IF NOT EXISTS idx_permission_grants_guild ON permission_grants(guild_id);

CREATE TABLE IF NOT EXISTS ai_custom_user_instructions (
    user_id BIGINT NOT NULL,
    instruction TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_ai_custom_user_instructions_user ON ai_custom_user_instructions(user_id);

CREATE TABLE IF NOT EXISTS birthdays (
    user_id BIGINT PRIMARY KEY,
    day INTEGER NOT NULL,
    month INTEGER NOT NULL,
    ping_on_servers SMALLINT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS birthday_channels (
    guild_id BIGINT PRIMARY KEY,
    channel_id BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS dm_opt_out (
    user_id BIGINT PRIMARY KEY,
    allow_dm SMALLINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS temp_voice_config (
    guild_id BIGINT PRIMARY KEY,
    lobby_channel_id BIGINT NOT NULL,
    category_id BIGINT,
    name_template TEXT
);

CREATE TABLE IF NOT EXISTS temp_voice_channels (
    channel_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS temp_voice_user_settings (
    user_id BIGINT PRIMARY KEY,
    name TEXT,
    user_limit INTEGER,
    locked SMALLINT NOT NULL DEFAULT 0,
    bitrate INTEGER,
    rtc_region TEXT
);

CREATE TABLE IF NOT EXISTS temp_voice_user_overwrites (
    user_id BIGINT NOT NULL,
    target_id BIGINT NOT NULL,
    allowed SMALLINT NOT NULL,
    PRIMARY KEY (user_id, target_id)
);

CREATE TABLE IF NOT EXISTS sticky_messages (
    channel_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    message_id BIGINT NOT NULL,
    created_by BIGINT NOT NULL
);
"""


def init():
    """Creates all tables if they don't exist yet. Safe to call multiple times."""
    global _initialized
    if _initialized:
        return

    with db_cursor(commit=True) as cur:
        cur.execute(SCHEMA)

    _initialized = True